/*
Accounts.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AuthViaPasswordRequestContract type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthViaPasswordRequestContract{}

// AuthViaPasswordRequestContract struct for AuthViaPasswordRequestContract
type AuthViaPasswordRequestContract struct {
	Email NullableString `json:"email,omitempty"`
	Password NullableString `json:"password,omitempty"`
}

// NewAuthViaPasswordRequestContract instantiates a new AuthViaPasswordRequestContract object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthViaPasswordRequestContract() *AuthViaPasswordRequestContract {
	this := AuthViaPasswordRequestContract{}
	return &this
}

// NewAuthViaPasswordRequestContractWithDefaults instantiates a new AuthViaPasswordRequestContract object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthViaPasswordRequestContractWithDefaults() *AuthViaPasswordRequestContract {
	this := AuthViaPasswordRequestContract{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthViaPasswordRequestContract) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthViaPasswordRequestContract) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *AuthViaPasswordRequestContract) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *AuthViaPasswordRequestContract) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *AuthViaPasswordRequestContract) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *AuthViaPasswordRequestContract) UnsetEmail() {
	o.Email.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthViaPasswordRequestContract) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthViaPasswordRequestContract) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *AuthViaPasswordRequestContract) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *AuthViaPasswordRequestContract) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *AuthViaPasswordRequestContract) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *AuthViaPasswordRequestContract) UnsetPassword() {
	o.Password.Unset()
}

func (o AuthViaPasswordRequestContract) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthViaPasswordRequestContract) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	return toSerialize, nil
}

type NullableAuthViaPasswordRequestContract struct {
	value *AuthViaPasswordRequestContract
	isSet bool
}

func (v NullableAuthViaPasswordRequestContract) Get() *AuthViaPasswordRequestContract {
	return v.value
}

func (v *NullableAuthViaPasswordRequestContract) Set(val *AuthViaPasswordRequestContract) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthViaPasswordRequestContract) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthViaPasswordRequestContract) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthViaPasswordRequestContract(val *AuthViaPasswordRequestContract) *NullableAuthViaPasswordRequestContract {
	return &NullableAuthViaPasswordRequestContract{value: val, isSet: true}
}

func (v NullableAuthViaPasswordRequestContract) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthViaPasswordRequestContract) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


