parameters:
  - name: appName
    type: string
  - name: imageName
    type: string
  - name: resourceManagerConnection
    type: string
  - name: resourceGroup
    type: string  
  - name: registryUri
    type: string
    

stages:
  - stage: DeployStage
    displayName: 'Deploy'
    jobs:
      - job: DeployJob
        displayName: 'Deployment Job'
        steps:
          - task: AzureWebAppContainer@1
            displayName: 'Azure Web App on Container Deploy: ${{ parameters.appName }}'
            inputs:
              azureSubscription: '${{ parameters.resourceManagerConnection }}'
              appName: '${{ parameters.appName }}'
              containers: '${{ parameters.registryUri }}/${{ parameters.imageName }}:$(Build.BuildId)'
          - task: AzureAppServiceSettings@1
            displayName: 'Azure App Service Settings: ${{ parameters.appName }}'
            inputs:
              azureSubscription: '${{ parameters.resourceManagerConnection }}'
              appName: '${{ parameters.appName }}'
              resourceGroupName: '${{ parameters.resourceGroup }}'
              connectionStrings: |
                [
                  {
                    "name": "AzureBlobStorage",
                    "value": "$(AzureBlobConnectionString)",
                    "type": "AzureBlobStorage"
                  }
                ]
              appSettings: |
                [
                  {
                    "name": "WEBSITES_PORT",
                    "value": "80",
                    "slotSetting": false
                  },
                  {
                    "name": "ASPNETCORE_ENVIRONMENT",
                    "value": "AzureDevelopment"
                  },
                  {
                    "name": "BACKEND_URI_CONVENTIONS",
                    "value": "https://catton-conventions.azurewebsites.net"
                  },
                  {
                    "name": "AZURE_KEY_VAULT_SECRET",
                    "value": "$(DomainKeyVaultSecret)"
                  },
                  {
                    "name": "USE_AZURE_KEY_VAULT",
                    "value": "true"
                  },
                  {
                    "name": "USE_BLOB_CONFIGURATION",
                    "value": "true"
                  },
                  {
                    "name": "ENABLE_SWAGGER",
                    "value": "true"
                  },
                  {
                    "name": "AZURE_BLOB_STORAGE_CONTAINER_NAME",
                    "value": "domain-config"
                  }
                ]