parameters:
  - name: registryConnection
    type: string
  - name: dockerFile
    type: string
  - name: imageName
    type: string
stages:
  - stage: BuildStage
    displayName: 'Build and Publish'
    jobs:
      - job: BuildJob
        displayName: 'Build and Publish Job'
        steps:
          - task: Docker@2
            displayName: 'Login to Azure Container Registry'
            inputs:
              containerRegistry: '${{ parameters.registryConnection }}'
              command: login
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: '${{ parameters.registryConnection }}'
              repository: '${{ parameters.imageName }}'
              command: 'buildAndPush'
              Dockerfile: '${{ parameters.dockerFile }}'