pool:
  vmImage: 'ubuntu-latest'

#variables:
##  buildPlatform: 'Any CPU'
##  buildConfiguration: 'Release'
##  resourceGroup: 'Catton'
##  registryConnection: 'CattonRegistryConnection'
##  resourceManagerConnection: 'CattonAzureResourceManagerConnection'
##  registryUri: 'cattonregistry.azurecr.io'

trigger:
  branches:
    include:
    - main

stages:
- template: Pipelines/domain-template.yaml
  parameters:
    appName: 'catton-api-gateway'
    projectPath: '**/ApiGateway'