pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  appName: 'catton-api-gateway'
  resourceGroup: 'Catton'
  registryConnection: 'CattonRegistryConnection'
  resourceManagerConnection: 'CattonAzureResourceManagerConnection'

  projectPath: '**/ApiGateway'
  dockerFile: '$(projectPath)/Dockerfile'
  imageName: '$(appName)'
  registryUri: 'cattonregistry.azurecr.io'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '$(projectPath)/*'

stages:
- template: Pipelines/domain-template.yaml
  parameters:
    appName: $(appName)
    projectPath: $(projectPath)