# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'




# Build Docker image
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 'CattonRegistry/test'
    command: build
    Dockerfile: 'Backend/Apigateway/Dockerfile' # Replace with your Dockerfile path
    tags: '$(Build.BuildId)'

# Login to Azure Container Registry
- task: Docker@2
  displayName: Login to Azure Container Registry
  inputs:
    containerRegistry: 'CattonRegistryConnection'
    command: login

# Push image to Azure Container Registry
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: 'CattonRegistryConnection'
    repository: 'CattonRegistry/test'
    command: push
    tags: '$(Build.BuildId)'