pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  appName: 'catton-api-gateway'
  resourceGroup: 'Catton'
  registryConnection: 'CattonRegistryConnection'
  resourceManagerConnection: 'CattonAzureResourceManagerConnection'

  projectPath: '**/ApiGateway'
  dockerFile: '*$(projectPath)/Dockerfile'
  imageName: '$(appName)'
  registryUri: 'cattonregistry.azurecr.io'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '$(projectPath)/*'

stages:
- template: Pipelines/domain-template.yml
  parameters:
    solution: $(solution)
    buildPlatform: $(buildPlatform)
    buildConfiguration: $(buildConfiguration)
    dockerFile: $(dockerFile)
    imageName: $(imageName)
    registryUri: $(registryUri)
    appName: $(appName)
    resourceGroup: $(resourceGroup)
    registryConnection: $(registryConnection)
    resourceManagerConnection: $(resourceManagerConnection)
