trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'Backend/ApiGateway/*'
      # Add additional project paths as needed

pr:
  branches:
    include:
      - '*'

stages:
  - stage: RunProjectA
    displayName: 'Run Project A'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    dependsOn: projectA
    jobs:
      - template: Backend/ApiGateway/azure-pipelines.yml

  # Add additional stages for other projects
