# File: pipeline.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  appName: 'catton-api-gateway'
  resourceGroup: 'Catton'
  registryConnection: 'CattonRegistryConnection'
  resourceManagerConnection: 'CattonAzureResourceManagerConnection'

  dockerFile: '**/ApiGateway/Dockerfile'
  imageName: '$(appName)'
  registryUri: 'cattonregistry.azurecr.io'


stages:
- template: Backend/ApiGateway/azure-pipelines.yml
  parameters:
    solution: $(solution)
    buildPlatform: $(buildPlatform)
    buildConfiguration: $(buildConfiguration)
    dockerFile: $(dockerFile)
    imageName: $(imageName)
    registryUri: $(registryUri)
    appName: $(appName)
    resourceGroup: $(resourceGroup)
    registryConnection: $(registryConnection)
    resourceManagerConnection: $(resourceManagerConnection)
