# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Login to Azure Container Registry
- task: Docker@2
  displayName: Login to Azure Container Registry
  inputs:
    containerRegistry: 'CattonRegistryConnection'
    command: login

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'tree /home/vsts/work/1'



# - task: Docker@2
#   inputs:
#     containerRegistry: 'CattonRegistryConnection'
#     repository: 'test'
#     command: 'buildAndPush'
#     Dockerfile: '$(buildConfiguration)/Backend/
- task: Docker@2
  inputs:
    containerRegistry: 'CattonRegistryConnection'
    repository: 'test'
    command: 'buildAndPush'
    Dockerfile: '**ApiGateway/Dockerfile'