version: '3.8'
services:
  sql_database:
    build:
      context: ./Backend/SqlDatabase
      dockerfile: Dockerfile
    ports:
       - "1433:1433"

  frontend:
    env_file:
      - dockerCompose.env
    build:
      context: ./Frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - API_BASE_PATH=https://api_gateway:5000

  api_gateway:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "4000:80"
      - "5000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true

  account_domain:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/Domains/Account
      dockerfile: Dockerfile
    ports:
      - "4001:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true