version: '3.8'

volumes: 
    data:
      driver: local
      driver_opts:
        type: none
        device: /mnt/data
        o: bind
    data_log:
        driver: local
        driver_opts:
            type: none
            device: /mnt/data_log/log
            o: bind
    secrets:
        driver: local
        driver_opts:
            type: none
            device: /mnt/secrets
            o: bind

services:
# === INFRASTRUCTURE === 
  sql_database:
    build:
      context: ./Backend/SqlDatabase
      dockerfile: Dockerfile
    ports:
       - "1433:1433"
    volumes:
      - data:/var/opt/mssql/data
      - data_log:/var/opt/mssql/log
      - secrets:/var/opt/mssql/secrets
      

# === FRONTEND === 
  frontend:
    env_file:
      - dockerCompose.env
    build:
      context: ./Frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "4269:80"
    environment:
      - API_BASE_PATH=https://host.docker.internal:5000

# === DOMAINS === 
  api_gateway:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "4000:80"
      - "5000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true
      - MIGRATE_DATABASE=true

  accounts_domain:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/Domains/Accounts
      dockerfile: Dockerfile
    ports:
      - "4001:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true
      - MIGRATE_DATABASE=true
  conventions_domain:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/Domains/Conventions
      dockerfile: Dockerfile
    ports:
      - "4002:80"
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true
      - MIGRATE_DATABASE=true
  payments_domain:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/Domains/Payments
      dockerfile: Dockerfile
    ports:
      - "4003:80"
      - "5003:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true
      - MIGRATE_DATABASE=true