version: '3.8'
services:
# === INFRASTRUCTURE === 
  sql_database:
    build:
      context: ./Backend/SqlDatabase
      dockerfile: Dockerfile
    ports:
       - "1433:1433"

# === FRONTEND === 
  frontend:
    env_file:
      - dockerCompose.env
    build:
      context: ./Frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "4269:80"
    environment:
      - API_BASE_PATH=https://host.docker.internal:5000

# === DOMAINS === 
  api_gateway:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "4000:80"
      - "5000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true

  account_domain:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/Domains/Account
      dockerfile: Dockerfile
    ports:
      - "4001:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true
  convention_domain:
    env_file:
      - dockerCompose.env
    build:
      context: ./Backend/Domains/ConventionDomain
      dockerfile: Dockerfile
    ports:
      - "4002:80"
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true