version: '3.8'
services:
  sql_database:
    build:
      context: ./SqlDatabase
      dockerfile: Dockerfile
    ports:
       - "1433:1433"

  api_gateway:
    env_file:
      - dockerCompose.env
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "4000:80"
      - "5000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true

  account_domain:
    env_file:
      - dockerCompose.env
    build:
      context: ./Domains/Account
      dockerfile: Dockerfile
    ports:
      - "4001:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ENABLE_SWAGGER=true