pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - main

stages:
- template: Pipelines/Templates/domain-template.yaml
  parameters:
    appName: 'catton-api-gateway'
    projectPath: '**/ApiGateway'