/*
Conventions.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// OrganizerAPIService OrganizerAPI service
type OrganizerAPIService service

type ApiApiConventionsConventionIdOrganizersGetRequest struct {
	ctx context.Context
	ApiService *OrganizerAPIService
	conventionId string
}

func (r ApiApiConventionsConventionIdOrganizersGetRequest) Execute() ([]OrganizerDto, *http.Response, error) {
	return r.ApiService.ApiConventionsConventionIdOrganizersGetExecute(r)
}

/*
ApiConventionsConventionIdOrganizersGet Method for ApiConventionsConventionIdOrganizersGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param conventionId
 @return ApiApiConventionsConventionIdOrganizersGetRequest
*/
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersGet(ctx context.Context, conventionId string) ApiApiConventionsConventionIdOrganizersGetRequest {
	return ApiApiConventionsConventionIdOrganizersGetRequest{
		ApiService: a,
		ctx: ctx,
		conventionId: conventionId,
	}
}

// Execute executes the request
//  @return []OrganizerDto
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersGetExecute(r ApiApiConventionsConventionIdOrganizersGetRequest) ([]OrganizerDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []OrganizerDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrganizerAPIService.ApiConventionsConventionIdOrganizersGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/conventions/{conventionId}/organizers"
	localVarPath = strings.Replace(localVarPath, "{"+"conventionId"+"}", url.PathEscape(parameterValueToString(r.conventionId, "conventionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiConventionsConventionIdOrganizersOrganizerIdDeleteRequest struct {
	ctx context.Context
	ApiService *OrganizerAPIService
	conventionId string
	organizerId string
}

func (r ApiApiConventionsConventionIdOrganizersOrganizerIdDeleteRequest) Execute() (*OrganizerDto, *http.Response, error) {
	return r.ApiService.ApiConventionsConventionIdOrganizersOrganizerIdDeleteExecute(r)
}

/*
ApiConventionsConventionIdOrganizersOrganizerIdDelete Method for ApiConventionsConventionIdOrganizersOrganizerIdDelete

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param conventionId
 @param organizerId
 @return ApiApiConventionsConventionIdOrganizersOrganizerIdDeleteRequest
*/
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersOrganizerIdDelete(ctx context.Context, conventionId string, organizerId string) ApiApiConventionsConventionIdOrganizersOrganizerIdDeleteRequest {
	return ApiApiConventionsConventionIdOrganizersOrganizerIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		conventionId: conventionId,
		organizerId: organizerId,
	}
}

// Execute executes the request
//  @return OrganizerDto
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersOrganizerIdDeleteExecute(r ApiApiConventionsConventionIdOrganizersOrganizerIdDeleteRequest) (*OrganizerDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OrganizerDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrganizerAPIService.ApiConventionsConventionIdOrganizersOrganizerIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/conventions/{conventionId}/organizers/{organizerId}"
	localVarPath = strings.Replace(localVarPath, "{"+"conventionId"+"}", url.PathEscape(parameterValueToString(r.conventionId, "conventionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"organizerId"+"}", url.PathEscape(parameterValueToString(r.organizerId, "organizerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiConventionsConventionIdOrganizersOrganizerIdGetRequest struct {
	ctx context.Context
	ApiService *OrganizerAPIService
	conventionId string
	organizerId string
}

func (r ApiApiConventionsConventionIdOrganizersOrganizerIdGetRequest) Execute() (*OrganizerDto, *http.Response, error) {
	return r.ApiService.ApiConventionsConventionIdOrganizersOrganizerIdGetExecute(r)
}

/*
ApiConventionsConventionIdOrganizersOrganizerIdGet Method for ApiConventionsConventionIdOrganizersOrganizerIdGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param conventionId
 @param organizerId
 @return ApiApiConventionsConventionIdOrganizersOrganizerIdGetRequest
*/
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersOrganizerIdGet(ctx context.Context, conventionId string, organizerId string) ApiApiConventionsConventionIdOrganizersOrganizerIdGetRequest {
	return ApiApiConventionsConventionIdOrganizersOrganizerIdGetRequest{
		ApiService: a,
		ctx: ctx,
		conventionId: conventionId,
		organizerId: organizerId,
	}
}

// Execute executes the request
//  @return OrganizerDto
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersOrganizerIdGetExecute(r ApiApiConventionsConventionIdOrganizersOrganizerIdGetRequest) (*OrganizerDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OrganizerDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrganizerAPIService.ApiConventionsConventionIdOrganizersOrganizerIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/conventions/{conventionId}/organizers/{organizerId}"
	localVarPath = strings.Replace(localVarPath, "{"+"conventionId"+"}", url.PathEscape(parameterValueToString(r.conventionId, "conventionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"organizerId"+"}", url.PathEscape(parameterValueToString(r.organizerId, "organizerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest struct {
	ctx context.Context
	ApiService *OrganizerAPIService
	conventionId string
	organizerId string
	organizerUpdateDto *OrganizerUpdateDto
}

func (r ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest) OrganizerUpdateDto(organizerUpdateDto OrganizerUpdateDto) ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest {
	r.organizerUpdateDto = &organizerUpdateDto
	return r
}

func (r ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest) Execute() (*OrganizerDto, *http.Response, error) {
	return r.ApiService.ApiConventionsConventionIdOrganizersOrganizerIdPutExecute(r)
}

/*
ApiConventionsConventionIdOrganizersOrganizerIdPut Method for ApiConventionsConventionIdOrganizersOrganizerIdPut

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param conventionId
 @param organizerId
 @return ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest
*/
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersOrganizerIdPut(ctx context.Context, conventionId string, organizerId string) ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest {
	return ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest{
		ApiService: a,
		ctx: ctx,
		conventionId: conventionId,
		organizerId: organizerId,
	}
}

// Execute executes the request
//  @return OrganizerDto
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersOrganizerIdPutExecute(r ApiApiConventionsConventionIdOrganizersOrganizerIdPutRequest) (*OrganizerDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OrganizerDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrganizerAPIService.ApiConventionsConventionIdOrganizersOrganizerIdPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/conventions/{conventionId}/organizers/{organizerId}"
	localVarPath = strings.Replace(localVarPath, "{"+"conventionId"+"}", url.PathEscape(parameterValueToString(r.conventionId, "conventionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"organizerId"+"}", url.PathEscape(parameterValueToString(r.organizerId, "organizerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.organizerUpdateDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiApiConventionsConventionIdOrganizersPostRequest struct {
	ctx context.Context
	ApiService *OrganizerAPIService
	conventionId string
	organizerCreateDto *OrganizerCreateDto
}

func (r ApiApiConventionsConventionIdOrganizersPostRequest) OrganizerCreateDto(organizerCreateDto OrganizerCreateDto) ApiApiConventionsConventionIdOrganizersPostRequest {
	r.organizerCreateDto = &organizerCreateDto
	return r
}

func (r ApiApiConventionsConventionIdOrganizersPostRequest) Execute() (*OrganizerDto, *http.Response, error) {
	return r.ApiService.ApiConventionsConventionIdOrganizersPostExecute(r)
}

/*
ApiConventionsConventionIdOrganizersPost Method for ApiConventionsConventionIdOrganizersPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param conventionId
 @return ApiApiConventionsConventionIdOrganizersPostRequest
*/
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersPost(ctx context.Context, conventionId string) ApiApiConventionsConventionIdOrganizersPostRequest {
	return ApiApiConventionsConventionIdOrganizersPostRequest{
		ApiService: a,
		ctx: ctx,
		conventionId: conventionId,
	}
}

// Execute executes the request
//  @return OrganizerDto
func (a *OrganizerAPIService) ApiConventionsConventionIdOrganizersPostExecute(r ApiApiConventionsConventionIdOrganizersPostRequest) (*OrganizerDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OrganizerDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrganizerAPIService.ApiConventionsConventionIdOrganizersPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/conventions/{conventionId}/organizers"
	localVarPath = strings.Replace(localVarPath, "{"+"conventionId"+"}", url.PathEscape(parameterValueToString(r.conventionId, "conventionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.organizerCreateDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
