/*
Conventions.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizerUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizerUpdateDto{}

// OrganizerUpdateDto struct for OrganizerUpdateDto
type OrganizerUpdateDto struct {
	Role *OrganizerRole `json:"role,omitempty"`
}

// NewOrganizerUpdateDto instantiates a new OrganizerUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizerUpdateDto() *OrganizerUpdateDto {
	this := OrganizerUpdateDto{}
	return &this
}

// NewOrganizerUpdateDtoWithDefaults instantiates a new OrganizerUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizerUpdateDtoWithDefaults() *OrganizerUpdateDto {
	this := OrganizerUpdateDto{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *OrganizerUpdateDto) GetRole() OrganizerRole {
	if o == nil || IsNil(o.Role) {
		var ret OrganizerRole
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizerUpdateDto) GetRoleOk() (*OrganizerRole, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *OrganizerUpdateDto) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given OrganizerRole and assigns it to the Role field.
func (o *OrganizerUpdateDto) SetRole(v OrganizerRole) {
	o.Role = &v
}

func (o OrganizerUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizerUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableOrganizerUpdateDto struct {
	value *OrganizerUpdateDto
	isSet bool
}

func (v NullableOrganizerUpdateDto) Get() *OrganizerUpdateDto {
	return v.value
}

func (v *NullableOrganizerUpdateDto) Set(val *OrganizerUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizerUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizerUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizerUpdateDto(val *OrganizerUpdateDto) *NullableOrganizerUpdateDto {
	return &NullableOrganizerUpdateDto{value: val, isSet: true}
}

func (v NullableOrganizerUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizerUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


