/*
Conventions.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AttendeeDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttendeeDto{}

// AttendeeDto struct for AttendeeDto
type AttendeeDto struct {
	AccountId *string `json:"accountId,omitempty"`
	ConventionId NullableString `json:"conventionId,omitempty"`
	CreatedDate *time.Time `json:"createdDate,omitempty"`
	AccountUsername NullableString `json:"accountUsername,omitempty"`
	AccountAvatarUri NullableString `json:"accountAvatarUri,omitempty"`
}

// NewAttendeeDto instantiates a new AttendeeDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttendeeDto() *AttendeeDto {
	this := AttendeeDto{}
	return &this
}

// NewAttendeeDtoWithDefaults instantiates a new AttendeeDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttendeeDtoWithDefaults() *AttendeeDto {
	this := AttendeeDto{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *AttendeeDto) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttendeeDto) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *AttendeeDto) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *AttendeeDto) SetAccountId(v string) {
	o.AccountId = &v
}

// GetConventionId returns the ConventionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AttendeeDto) GetConventionId() string {
	if o == nil || IsNil(o.ConventionId.Get()) {
		var ret string
		return ret
	}
	return *o.ConventionId.Get()
}

// GetConventionIdOk returns a tuple with the ConventionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AttendeeDto) GetConventionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConventionId.Get(), o.ConventionId.IsSet()
}

// HasConventionId returns a boolean if a field has been set.
func (o *AttendeeDto) HasConventionId() bool {
	if o != nil && o.ConventionId.IsSet() {
		return true
	}

	return false
}

// SetConventionId gets a reference to the given NullableString and assigns it to the ConventionId field.
func (o *AttendeeDto) SetConventionId(v string) {
	o.ConventionId.Set(&v)
}
// SetConventionIdNil sets the value for ConventionId to be an explicit nil
func (o *AttendeeDto) SetConventionIdNil() {
	o.ConventionId.Set(nil)
}

// UnsetConventionId ensures that no value is present for ConventionId, not even an explicit nil
func (o *AttendeeDto) UnsetConventionId() {
	o.ConventionId.Unset()
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *AttendeeDto) GetCreatedDate() time.Time {
	if o == nil || IsNil(o.CreatedDate) {
		var ret time.Time
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttendeeDto) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *AttendeeDto) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given time.Time and assigns it to the CreatedDate field.
func (o *AttendeeDto) SetCreatedDate(v time.Time) {
	o.CreatedDate = &v
}

// GetAccountUsername returns the AccountUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AttendeeDto) GetAccountUsername() string {
	if o == nil || IsNil(o.AccountUsername.Get()) {
		var ret string
		return ret
	}
	return *o.AccountUsername.Get()
}

// GetAccountUsernameOk returns a tuple with the AccountUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AttendeeDto) GetAccountUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountUsername.Get(), o.AccountUsername.IsSet()
}

// HasAccountUsername returns a boolean if a field has been set.
func (o *AttendeeDto) HasAccountUsername() bool {
	if o != nil && o.AccountUsername.IsSet() {
		return true
	}

	return false
}

// SetAccountUsername gets a reference to the given NullableString and assigns it to the AccountUsername field.
func (o *AttendeeDto) SetAccountUsername(v string) {
	o.AccountUsername.Set(&v)
}
// SetAccountUsernameNil sets the value for AccountUsername to be an explicit nil
func (o *AttendeeDto) SetAccountUsernameNil() {
	o.AccountUsername.Set(nil)
}

// UnsetAccountUsername ensures that no value is present for AccountUsername, not even an explicit nil
func (o *AttendeeDto) UnsetAccountUsername() {
	o.AccountUsername.Unset()
}

// GetAccountAvatarUri returns the AccountAvatarUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AttendeeDto) GetAccountAvatarUri() string {
	if o == nil || IsNil(o.AccountAvatarUri.Get()) {
		var ret string
		return ret
	}
	return *o.AccountAvatarUri.Get()
}

// GetAccountAvatarUriOk returns a tuple with the AccountAvatarUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AttendeeDto) GetAccountAvatarUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountAvatarUri.Get(), o.AccountAvatarUri.IsSet()
}

// HasAccountAvatarUri returns a boolean if a field has been set.
func (o *AttendeeDto) HasAccountAvatarUri() bool {
	if o != nil && o.AccountAvatarUri.IsSet() {
		return true
	}

	return false
}

// SetAccountAvatarUri gets a reference to the given NullableString and assigns it to the AccountAvatarUri field.
func (o *AttendeeDto) SetAccountAvatarUri(v string) {
	o.AccountAvatarUri.Set(&v)
}
// SetAccountAvatarUriNil sets the value for AccountAvatarUri to be an explicit nil
func (o *AttendeeDto) SetAccountAvatarUriNil() {
	o.AccountAvatarUri.Set(nil)
}

// UnsetAccountAvatarUri ensures that no value is present for AccountAvatarUri, not even an explicit nil
func (o *AttendeeDto) UnsetAccountAvatarUri() {
	o.AccountAvatarUri.Unset()
}

func (o AttendeeDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttendeeDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if o.ConventionId.IsSet() {
		toSerialize["conventionId"] = o.ConventionId.Get()
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if o.AccountUsername.IsSet() {
		toSerialize["accountUsername"] = o.AccountUsername.Get()
	}
	if o.AccountAvatarUri.IsSet() {
		toSerialize["accountAvatarUri"] = o.AccountAvatarUri.Get()
	}
	return toSerialize, nil
}

type NullableAttendeeDto struct {
	value *AttendeeDto
	isSet bool
}

func (v NullableAttendeeDto) Get() *AttendeeDto {
	return v.value
}

func (v *NullableAttendeeDto) Set(val *AttendeeDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAttendeeDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAttendeeDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttendeeDto(val *AttendeeDto) *NullableAttendeeDto {
	return &NullableAttendeeDto{value: val, isSet: true}
}

func (v NullableAttendeeDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttendeeDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


