/*
Conventions.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AttendeeCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttendeeCreateDto{}

// AttendeeCreateDto struct for AttendeeCreateDto
type AttendeeCreateDto struct {
	AccountId *string `json:"accountId,omitempty"`
}

// NewAttendeeCreateDto instantiates a new AttendeeCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttendeeCreateDto() *AttendeeCreateDto {
	this := AttendeeCreateDto{}
	return &this
}

// NewAttendeeCreateDtoWithDefaults instantiates a new AttendeeCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttendeeCreateDtoWithDefaults() *AttendeeCreateDto {
	this := AttendeeCreateDto{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *AttendeeCreateDto) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttendeeCreateDto) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *AttendeeCreateDto) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *AttendeeCreateDto) SetAccountId(v string) {
	o.AccountId = &v
}

func (o AttendeeCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttendeeCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	return toSerialize, nil
}

type NullableAttendeeCreateDto struct {
	value *AttendeeCreateDto
	isSet bool
}

func (v NullableAttendeeCreateDto) Get() *AttendeeCreateDto {
	return v.value
}

func (v *NullableAttendeeCreateDto) Set(val *AttendeeCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAttendeeCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAttendeeCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttendeeCreateDto(val *AttendeeCreateDto) *NullableAttendeeCreateDto {
	return &NullableAttendeeCreateDto{value: val, isSet: true}
}

func (v NullableAttendeeCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttendeeCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


