parameters:
  - name: projectPath
    type: string
  - name: appName
    type: string

stages:
  - template: /Pipelines/Templates/general-domain-template.yaml
    parameters:
      dockerFile: '${{ parameters.projectPath }}/Dockerfile'
      imageName: '${{ parameters.appName }}'
      registryUri: 'cattonregistry.azurecr.io'
      appName: '${{ parameters.appName }}'
      resourceGroup: 'Catton'
      registryConnection: 'CattonRegistryConnection'
      resourceManagerConnection: 'CattonAzureResourceManagerConnection'
      projectPath: '${{ parameters.projectPath }}'