parameters:
  - name: dockerFile
    type: string
  - name: imageName
    type: string
  - name: registryUri
    type: string
  - name: appName
    type: string
  - name: resourceGroup
    type: string
  - name: registryConnection
    type: string
  - name: resourceManagerConnection
    type: string
  - name: projectPath
    type: string

stages:
  - template: /Pipelines/StageTemplates/asp-test-template.yaml
    parameters:
      projectPath: '${{ parameters.projectPath }}'
      
  - template: /Pipelines/StageTemplates/asp-build-template.yaml
    parameters:
      registryConnection: '${{ parameters.registryConnection }}'
      dockerFile: '${{ parameters.dockerFile }}'
      imageName: '${{ parameters.imageName }}'

  - template: /Pipelines/StageTemplates/asp-deploy-template.yaml
    parameters:
      appName: '${{ parameters.appName }}'
      imageName: '${{ parameters.imageName }}'
      resourceManagerConnection: '${{ parameters.resourceManagerConnection }}'
      resourceGroup: '${{ parameters.resourceGroup }}'
      registryUri: '${{ parameters.registryUri }}'

