pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'Domain Secrets'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**/Domains/Conventions/*'

stages:
    - template: /Pipelines/Templates/domain-template.yaml
      parameters:
        appName: 'catton-conventions'
        projectPath: '**/Domains/Conventions'