parameters:
  - name: projectName
    type: string
  - name: projectPath
    type: string
  - name: appName
    type: string

stages:
  - template: Pipelines/domain-template.yml
    parameters:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      dockerFile: '${{ parameters.projectPath }}/Dockerfile'
      imageName: '${{ parameters.projectName }}'
      registryUri: 'cattonregistry.azurecr.io'
      appName: ${{ parameters.appName }}'
      resourceGroup: 'Catton'
      registryConnection: 'CattonRegistryConnection'
      resourceManagerConnection: 'CattonAzureResourceManagerConnection'
      projectPath: '${{ projectPath }}'