/**
 * Payments.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CheckoutSessionDetailsDto } from './checkoutSessionDetailsDto';
import { PaymentStatus } from './paymentStatus';


export interface PaymentDto { 
    id?: string;
    amount?: number;
    checkoutSession?: CheckoutSessionDetailsDto;
    paymentStatus?: PaymentStatus;
    currency?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
}
export namespace PaymentDto {
}


