/**
 * Conventions.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizerRole } from './organizerRole';


export interface OrganizerDto { 
    accountId?: string;
    conventionId?: string | null;
    createdDate?: string;
    role?: OrganizerRole;
    accountUsername?: string | null;
    accountAvatarUri?: string | null;
}
export namespace OrganizerDto {
}


