/**
 * Conventions.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OrganizerRole = 'Guest' | 'Owner' | 'Administrator' | 'Moderator' | 'Announcer' | 'Helper';

export const OrganizerRole = {
    Guest: 'Guest' as OrganizerRole,
    Owner: 'Owner' as OrganizerRole,
    Administrator: 'Administrator' as OrganizerRole,
    Moderator: 'Moderator' as OrganizerRole,
    Announcer: 'Announcer' as OrganizerRole,
    Helper: 'Helper' as OrganizerRole
};

