/**
 * Conventions.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PaymentStatus = 'Pending' | 'Succeeded' | 'Failed';

export const PaymentStatus = {
    Pending: 'Pending' as PaymentStatus,
    Succeeded: 'Succeeded' as PaymentStatus,
    Failed: 'Failed' as PaymentStatus
};

