/**
 * Conventions.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TicketTemplateDto { 
    id?: string;
    name?: string | null;
    description?: string | null;
    price?: number;
    avaliable?: boolean;
    createDate?: string;
    convetionId?: string | null;
    lastEditAuthorId?: string | null;
    authorId?: string;
}

