/*
Conventions.Api

Testing TicketTemplateAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_TicketTemplateAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TicketTemplateAPIService ApiConventionsConventionIdTicketTemplatesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string

		resp, httpRes, err := apiClient.TicketTemplateAPI.ApiConventionsConventionIdTicketTemplatesGet(context.Background(), conventionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketTemplateAPIService ApiConventionsConventionIdTicketTemplatesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string

		resp, httpRes, err := apiClient.TicketTemplateAPI.ApiConventionsConventionIdTicketTemplatesPost(context.Background(), conventionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketTemplateAPIService ApiConventionsConventionIdTicketTemplatesTicketTemplateIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var ticketTemplateId string

		resp, httpRes, err := apiClient.TicketTemplateAPI.ApiConventionsConventionIdTicketTemplatesTicketTemplateIdDelete(context.Background(), conventionId, ticketTemplateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketTemplateAPIService ApiConventionsConventionIdTicketTemplatesTicketTemplateIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var ticketTemplateId string

		resp, httpRes, err := apiClient.TicketTemplateAPI.ApiConventionsConventionIdTicketTemplatesTicketTemplateIdGet(context.Background(), conventionId, ticketTemplateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketTemplateAPIService ApiConventionsConventionIdTicketTemplatesTicketTemplateIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var ticketTemplateId string

		resp, httpRes, err := apiClient.TicketTemplateAPI.ApiConventionsConventionIdTicketTemplatesTicketTemplateIdPut(context.Background(), conventionId, ticketTemplateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
