/*
Conventions.Api

Testing TicketAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_TicketAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TicketAPIService ApiConventionsConventionIdAttendeesAttendeeIdTicketsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var attendeeId string

		resp, httpRes, err := apiClient.TicketAPI.ApiConventionsConventionIdAttendeesAttendeeIdTicketsGet(context.Background(), conventionId, attendeeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketAPIService ApiConventionsConventionIdAttendeesAttendeeIdTicketsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var attendeeId string

		resp, httpRes, err := apiClient.TicketAPI.ApiConventionsConventionIdAttendeesAttendeeIdTicketsPost(context.Background(), conventionId, attendeeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketAPIService ApiConventionsConventionIdAttendeesAttendeeIdTicketsTicketIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var ticketId string
		var attendeeId string

		resp, httpRes, err := apiClient.TicketAPI.ApiConventionsConventionIdAttendeesAttendeeIdTicketsTicketIdDelete(context.Background(), conventionId, ticketId, attendeeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketAPIService ApiConventionsConventionIdAttendeesAttendeeIdTicketsTicketIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var ticketId string
		var attendeeId string

		resp, httpRes, err := apiClient.TicketAPI.ApiConventionsConventionIdAttendeesAttendeeIdTicketsTicketIdPut(context.Background(), conventionId, ticketId, attendeeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketAPIService ApiConventionsConventionIdTicketsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string

		resp, httpRes, err := apiClient.TicketAPI.ApiConventionsConventionIdTicketsGet(context.Background(), conventionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TicketAPIService ApiConventionsConventionIdTicketsTicketIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var conventionId string
		var ticketId string

		resp, httpRes, err := apiClient.TicketAPI.ApiConventionsConventionIdTicketsTicketIdGet(context.Background(), conventionId, ticketId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
